version: "2"
services:
  frontend:
    build: frontend
    ports:
      - "5000:5000"
    container_name: front-container
    restart: always
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"